services:
  mongo:
    image: mongo
    restart: unless-stopped
    env_file: stack.env
    volumes:
      - didjo_mongo_db:/data/db

  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: stack.env
    depends_on:
      - mongo
    ports:
      - "9441:8000"

volumes:
  didjo_mongo_db: