services:
  mongo:
    image: mongo
    restart: always
    env_file: stack.env
    volumes:
      - ./mongo-data:/data/db

  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - mongo
    ports:
      - "9441:8000"
    env_file: stack.env
